"""add batch schedule exceptions

Revision ID: 24a7389003e8
Revises: 49642d48983f
Create Date: 2026-08-21 09:21:46.900778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a7389003e8'
down_revision: Union[str, Sequence[str], None] = '49642d48983f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('compensation_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_schedule_exceptions_batch_id'), 'batch_schedule_exceptions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_schedule_exceptions_compensation_date'), 'batch_schedule_exceptions', ['compensation_date'], unique=False)
    op.create_index(op.f('ix_batch_schedule_exceptions_created_by'), 'batch_schedule_exceptions', ['created_by'], unique=False)
    op.create_index(op.f('ix_batch_schedule_exceptions_id'), 'batch_schedule_exceptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_schedule_exceptions_id'), table_name='batch_schedule_exceptions')
    op.drop_index(op.f('ix_batch_schedule_exceptions_created_by'), table_name='batch_schedule_exceptions')
    op.drop_index(op.f('ix_batch_schedule_exceptions_compensation_date'), table_name='batch_schedule_exceptions')
    op.drop_index(op.f('ix_batch_schedule_exceptions_batch_id'), table_name='batch_schedule_exceptions')
    op.drop_table('batch_schedule_exceptions')
    # ### end Alembic commands ###
