"""make optional student fields nullable

Revision ID: 49642d48983f
Revises: e596a7277ab2
Create Date: 2026-08-17 01:21:34.119894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49642d48983f'
down_revision: Union[str, Sequence[str], None] = 'e596a7277ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('students', 'join_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'emergency_contact',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'emergency_contact',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'join_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
