"""make original_date nullable for extra classes

Revision ID: ce85619a55ef
Revises: 24a7389003e8
Create Date: 2026-08-21 09:39:32.159999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce85619a55ef'
down_revision: Union[str, Sequence[str], None] = '24a7389003e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_schedule_exceptions', 'original_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_schedule_exceptions', 'original_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
