"""update batch name uniqueness

Revision ID: eebf342f767d
Revises: f6313908a061
Create Date: 2026-08-12 14:28:35.131884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebf342f767d'
down_revision: Union[str, Sequence[str], None] = 'f6313908a061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('batches_batch_name_key'), 'batches', type_='unique')
    op.create_index('uq_batches_active_batch_name', 'batches', ['batch_name'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_batches_active_batch_name', table_name='batches', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('batches_batch_name_key'), 'batches', ['batch_name'])
    # ### end Alembic commands ###
